// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrate CLI, pgbouncer üzerinden gelen advisory-lock kısıtlarına takılmaması
    // için doğrudan (unpooled) bağlantıyı kullanır; uygulama çalışma zamanında
    // ayrıca src/lib/prisma.ts içinden havuzlu (pooled) DATABASE_URL'i kullanır.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
